---
- name: Harden Iptables

  hosts: javadev
  become_user: root
  become: true
  become_method: sudo

  tasks:

    - name: Install firewalld
      yum: name=firewalld state=present
      become: yes

    - name: Verify Iptables is enabled and running
      service: name=firewalld state=started enabled=yes
      become: yes

    - name: Allow related and established connections
    # Added to accept established and related connections, typical rule
      command: firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -m state --state ESTABLISHED,RELATED -j ACCEPT
      become: yes

    - name: Enable net.ipv4 forwarding #Required? if host has more than 1 ipv4 address
      command: echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
      command: sysctl -p 
      become: yes

    - name: Allow Wildfly ports inbound
      firewalld:
           port: 8080/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly ports inbound
      firewalld:
           port: 8185/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly ports inbound
      firewalld:
           port: 8285/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly ports inbound
      firewalld:
           port: 8385/tcp
           permanent: true
           state: enabled

    - name: Allow mgmt ports
      firewalld:
           port: 22/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly Mgmt ports
      firewalld:
           port: 10095/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly Mgmt ports
      firewalld:
           port: 10195/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly Mgmt ports
      firewalld:
           port: 10295/tcp
           permanent: true
           state: enabled

    - name: Allow Wildfly Mgmt ports
      firewalld:
           port: 9990/tcp
           permanent: true
           state: enabled

    - name: Reload Firewalld to confirm changes
      command: firewall-cmd --Reload
      become: yes
      