---
- hosts: javadev
  tasks:
  - name: To restrict access to cron and at
     command: |
         touch /etc/cron.allow
         chmod 600 /etc/cron.allow
         awk -F: '{print $1}' /etc/passwd | grep -v root > /etc/cron.deny
         touch /etc/at.allow
         chmod 600 /etc/at.allow
         awk -F: '{print $1}' /etc/passwd | grep -v root > /etc/at.deny
     become: yes  
