---
- name: Setting the automation users password for dev
  hosts: dev_linux
  vars:
    password: $6$rounds=656000$hCsG49bkvJbbIJRn$n17tmZrJ8NDoTftnv4zFSkYMP5dOJMQD.lAy97WzXPEV0TL53dpdtNfZBAc6WbAkWh7IogRdORcx6Nn6dolKf1
  #hased passwd created via: python -c "from passlib.hash import sha512_crypt; import 
  #getpass; print sha512_crypt.encrypt(getpass.getpass())"
  tasks:
  - user: name=automation password={{ password }}
